name: aams_fyp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.3
  freezed: ^2.0.5
  bloc: ^8.0.3
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  table_calendar: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Poppins
      fonts:
          - asset: assets/fonts/Poppins-Regular.ttf
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Poppins-Medium.ttf
            weight: 500
          - asset: assets/fonts/Poppins-Bold.ttf
            weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700